Add files via upload

diff --git a/easykube/easykube b/easykube/easykube
--- a/easykube/easykube
+++ b/easykube/easykube
@@ -5,6 +5,10 @@
 #       pod
 #       svc
 #       deployment
+#   check:
+#       make a flow
+#   db:
+#       restore from dump
 
 ###COLORLS###
 #LIGHT COLORS#
@@ -22,16 +26,49 @@ NC='\033[0m' #No color
 ###POD STATES###
 PODOK=("Running")
 PODERR=("CrashLoopBackOff" "Error" "Failed" "ImagePullBackOff" "ErrImagePull" "Unknow")
-PODNONE=("Completed" "Terminating" "Init" "Waiting" "Pending")
+PODNONE=("Completed" "Terminating" "Init" "Waiting" "Pending" "ContainerCreating")
 
+
+if [[ $USER != 'root' ]]; then
+    if [[ ! -d "/home/$USER/.easykube/" ]]; then
+        mkdir /home/$USER/.easykube/
+    fi
+    CONFIGFILE="/home/$USER/.easykube/config.json"
+    CONNFILE="/home/$USER/.easykube/connections.json"
+else
+    if [[ ! -d " /root/.easykube/" ]]; then
+        mkdir /root/.easykube/
+    fi
+    CONFIGFILE="/root/.easykube/config.json"
+    CONNFILE="/root/.easykube/connections.json"
+fi
+
+if [[ ! -e $CONFIGFILE ]]; then
+    touch $CONFIGFILE
+    chmod 775 $CONFIGFILE
+    echo '{"kubeconfig":"'$(kubectl config current-context)'"}' | jq > $CONFIGFILE
+fi
+
+if [[ ! -e $CONNFILE ]]; then
+    touch $CONNFILE
+    chmod 775 $CONNFILE
+    echo '[]' | jq > $CONNFILE
+fi
 #TABLEVIEW=$(awk '{printf "%-0s %-5s %-50s %-25s %-5s %-0s\n" ,$1,$2,$3,$4,$5,$6}') #why the fuck it isn't works?..
+table6(){
+    awk '{printf "%-0s %-5s %-60s %-25s %-5s %-0s\n" ,$1,$2,$3,$4,$5,$6}'
+}
+
+table3(){
+    awk '{printf "%-0s %-5s %-50s\n" ,$1,$2,$3}'
+}
 
 dbPass(){
     #in future - make a json map for secrets
     dbHelp(){
         echo "Usage:
-    easykube db [namespace] [action]
-Actions:
+    easykube db [namespace] [action]"
+        echo "Actions:
     pass - show db password
     connect - connect to db
     dump - make db dump"
@@ -44,13 +81,17 @@ Actions:
         exit 0
     }
 
-    if { [[ $1 =~ "help" ]] || [[ -z $1 || -z $2 ]];  }; then
-        dbHelp
+    if { [[ $2 =~ "help" ]] || [[ -z $3 || -z $2 ]]; }; then
+        if [[ -z $2 ]]; then
+            echo -e "${RED}Namespace is not defined${NC}"
+        fi
+        $1Help
     fi
-    NS=$1
-    DBPASS=$(kubectl -n $NS get secret db-postgresql -o=jsonpath='{.data.postgresql-password}' | base64 -d)
 
-    case $2 in
+    NS=$2
+    DBPASS=$(kubectl -n $NS get secret db-postgresql -o=jsonpath='{.data.postgresql-password}' | base64 -d || echo "Could not find secret" && exit 1)
+
+    case $3 in
         connect) dbConnect $NS $DBPASS
         ;;
         dump) dbDump $NS $DBPASS
@@ -123,7 +164,7 @@ dbDump(){
         choosePod ${pods[@]}
     fi
 
-    echo -e "Enter dir where dump will be placed. Example: /tmp. Default is ./: \c"
+    echo -e "Enter dir where dump will be placed. Example: /tmp. Default is current directory: \c"
     read -r dumpdir
     if [[ -z $dumpdir ]]; then
         dumpdir="./"
@@ -145,9 +186,15 @@ dbDump(){
 
 }
 
+dbRestore(){
+    #kubectl -n $NS sca
+    #kubectl -n $NS get pod db-postgresql-0 -o json | jq ".spec.volumes [0].persistentVolumeClaim.claimName " -r
+    exit 0
+}
+
 exe(){
-    NS=$1
-    cmd=$2
+    NS=$2
+    #cmd=$3
 
     exeHelp(){
         echo "kubectl exec"
@@ -155,10 +202,17 @@ exe(){
         exit 1
     }
 
-    if { [[ $1 =~ "help" ]] || [[ -z $1 || -z $2 ]]; }; then
-        exeHelp
-        exit 1
+    if { [[ $2 =~ "help" ]] || [[ -z $3 || -z $2 ]]; }; then
+        if [[ -z $2 ]]; then
+            echo -e "${RED}Namespace is not defined${NC}"
+        fi
+        $1Help
     fi
+
+    while [ -n "$3" ]; do
+        cmd+=$3" "
+        shift
+    done
 
     IFS=" " read -a pods <<< $(echo $(kubectl -n $NS get pods | grep -v "NAME" |  awk '{print $1"@"$3}'))
 
@@ -170,13 +224,13 @@ exe(){
             podstate=$(echo ${pods[i]} | cut -d"@" -f2)
 
             if [[ "${PODOK[*]}" =~ "${podstate}" ]]; then
-                echo -e "   ${GREEN} [$a]: $pod${NC}" | awk '{printf "%-0s %-5s %-50s\n" ,$1,$2,$3}'
+                echo -e "   ${GREEN} [$a]: $pod${NC}" | table3
                 ((a++))
                 exepods+=($pod)
             elif [[ "${PODNONE[*]}" =~ "${podstate}"  ]]; then
-                echo -e "   ${GRAY} [-]: $pod${NC}" | awk '{printf "%-0s %-5s %-50s\n" ,$1,$2,$3}'
+                echo -e "   ${GRAY} [-]: $pod${NC}" | table3
             else
-                echo -e "   ${RED} [-]: $pod${NC}" | awk '{printf "%-0s %-5s %-50s\n" ,$1,$2,$3}'
+                echo -e "   ${RED} [-]: $pod${NC}" | table3
             fi
     done
 
@@ -196,24 +250,19 @@ exe(){
 
 }
 
-
-
 podLogs(){
-    NS=$1
+    NS=$2
 
-    if [[ -z $NS ]]; then
-        echo -e "${RED}Namespace is not defined${NC}"
-        exit 1
+    if { [[ $2 =~ "help" ]] || [[ -z $3 || -z $2 ]]; }; then
+        if [[ -z $2 ]]; then
+            echo -e "${RED}Namespace is not defined${NC}"
+        fi
+        $1Help
     fi
 
-    if { [[ $1 =~ "help"  || -z $1 ]]; }; then
-        echo "Usage: easykube logs [namespase]"
-        exit 1
-    fi
+    if [[ -z $3 ]]; then
 
-    if [[ -z $2 ]]; then
-
-        IFS=" " read -a pods <<< $(echo $(kubectl -n $NS get pods | grep -v "NAME" | awk '{print $1"@"$3}'))
+        IFS=" " read -a pods <<< $(echo $(kubectl -n $NS get pods | grep -v "NAME" | awk '{print $1"@"$3"@"$4}'))
 
         echo "List of pods:"
         a=0
@@ -223,13 +272,13 @@ podLogs(){
             podstate=$(echo ${pods[i]} | cut -d"@" -f2)
 
             if [[ "${PODOK[*]}" =~ "${podstate}" ]]; then
-                echo -e "   ${GREEN} [$a]: $pod${NC}" | awk '{printf "%-0s %-5s %-50s\n" ,$1,$2,$3}'
+                echo -e "   ${GREEN} [$a]: $pod${NC}" | table3
                 ((a++))
                 exepods+=($pod)
             elif [[ "${PODNONE[*]}" =~ "${podstate}"  ]]; then
-                echo -e "   ${GRAY} [-]: $pod${NC}" | awk '{printf "%-0s %-5s %-50s\n" ,$1,$2,$3}'
+                echo -e "   ${GRAY} [-]: $pod${NC}" | table3
             else
-                echo -e "   ${RED} [$a]: $pod${NC}" | awk '{printf "%-0s %-5s %-50s\n" ,$1,$2,$3}'
+                echo -e "   ${RED} [$a]: $pod${NC}" | table3
                 ((a++))
                 exepods+=($pod)
             fi
@@ -243,7 +292,7 @@ podLogs(){
         read -r c
         pod=${exepods[c]}
     else
-        pod=$2
+        pod=$3
     fi
     container=$(kubectl -n $NS get pod $pod -o=jsonpath={'.spec.containers[0].name'})
     echo ""
@@ -256,49 +305,68 @@ podLogs(){
 
 checkPods(){
 
-    if { [[ $1 =~ "help" ]] || [[ -z $2 || -z $1 ]]; }; then
-        echo "Usage: easykube check [namespase] [option]"
+    checkHelp(){
+        echo "Usage: easykube check [namespase] [option] watch(optional)"
         echo "Actions:"
         echo "  all - show all state pods"
         echo "  warn - show pods with restarts"
         echo "  err - show pods with errors"
         exit 1
-    fi
+    }
 
     afterRun(){
         exepods=$@
+
+        echo -e "\nChoose pod to view its log or press ^C: \c"
+        read -r b
+
         if [[ -z $exepods ]]; then
             echo -e "\nNo pods available" && exit 1
         fi
 
-        echo -e "Choose pod to view its log or press ^C: \c"
-        read -r b
-
-        podLogs $NS ${exepods[b]}
+        podLogs "logs" $NS ${exepods[b]}
     }
 
     all(){
-        NS=$1
-        a=0
-        for (( i=0; i<${#pods[@]}; i++ )); do
-            pod=$(echo ${pods[i]} | cut -d"@" -f1)
-            podstate=$(echo ${pods[i]} | cut -d"@" -f2)
-            podrestarts=$(echo ${pods[i]} | cut -d"@" -f3)
-            if [[ "${PODOK[*]}" =~ "${podstate}" ]]; then
-               echo -e "   ${GREEN} [$a]: $pod $podstate $podrestarts ${NC}" | awk '{printf "%-0s %-5s %-50s %-25s %-5s %-0s\n" ,$1,$2,$3,$4,$5,$6}'
-                ((a++))
-                exepods+=($pod)
-            elif [[ "${PODNONE[*]}" =~ "${podstate}"  ]]; then
-                echo -e "   ${GRAY} [-]: $pod $podstate $podrestarts ${NC}" | awk '{printf "%-0s %-5s %-50s %-25s %-5s %-0s\n" ,$1,$2,$3,$4,$5,$6}'
-            else
-                echo -e "   ${RED} [$a]: $pod $podstate $podrestarts ${NC}" | awk '{printf "%-0s %-5s %-50s %-25s %-5s %-0s\n" ,$1,$2,$3,$4,$5,$6}'
-                ((a++))
-                exepods+=($pod)
-            fi
-        done
+        show(){
+            a=0
+            for (( i=0; i<${#pods[@]}; i++ )); do
+                pod=$(echo ${pods[i]} | cut -d"@" -f1)
+                podstate=$(echo ${pods[i]} | cut -d"@" -f2)
+                podrestarts=$(echo ${pods[i]} | cut -d"@" -f3)
+                if { [[ "${PODOK[*]}" =~ "${podstate}" && $podrestarts -gt 0 ]]; }; then
+                    echo -e "   ${YELLOW} [$a]: $pod $podstate $podrestarts ${NC}" | table6
+                    ((a++))
+                    exepods+=($pod)
+                elif [[ "${PODNONE[*]}" =~ "${podstate}"  ]]; then
+                    echo -e "   ${DGRAY} [-]: $pod $podstate $podrestarts ${NC}" | table6
+                    exepods+=($pod)
+                elif [[ "${PODOK[*]}" =~ "${podstate}" ]];  then
+                    echo -e "   ${GREEN} [$a]: $pod $podstate $podrestarts ${NC}" | table6
+                    ((a++))
+                    exepods+=($pod)
+                else
+                    echo -e "   ${RED} [$a]: $pod $podstate $podrestarts ${NC}" | table6
+                    ((a++))
+                    exepods+=($pod)
+                fi
+            done
+        }
 
-        afterRun ${exepods[@]}
-
+        if [[ -z $1 ]]; then
+            show
+            exit 0
+            afterRun ${exepods[@]}
+        else
+            while true ; do
+                tput el
+                show
+                if [[ -z $exepods ]]; then
+                    echo -e "\nNo pods available" && exit 1
+                fi
+                sleep 5
+            done
+        fi
     }
 
     warn(){
@@ -308,7 +376,7 @@ checkPods(){
             podstate=$(echo ${pods[i]} | cut -d"@" -f2)
             podrestarts=$(echo ${pods[i]} | cut -d"@" -f3)
             if { [[ "${PODOK[*]}" =~ "${podstate}" && $podrestarts -gt 0 ]]; }; then
-                echo -e "   ${YELLOW}[$a]: $pod $podstate $podrestarts ${NC}" | '{printf "%-0s %-5s %-50s %-25s %-5s %-0s\n" ,$1,$2,$3,$4,$5,$6}'
+                echo -e "   ${YELLOW} [$a]: $pod $podstate $podrestarts ${NC}" | table6
                 ((a++))
                 exepods+=($pod)
             fi
@@ -323,7 +391,7 @@ checkPods(){
             podstate=$(echo ${pods[i]} | cut -d"@" -f2)
             podrestarts=$(echo ${pods[i]} | cut -d"@" -f3)
             if [[ "${PODERR[*]}" =~ "${podstate}" ]]; then
-                echo -e "   ${RED}[$a]: $pod $podstate $podrestarts ${NC}" | '{printf "%-0s %-5s %-50s %-25s %-5s %-0s\n" ,$1,$2,$3,$4,$5,$6}'
+                echo -e "   ${RED}[$a]: $pod $podstate $podrestarts ${NC}" | table6
                 ((a++))
                 exepods+=($pod)
             fi
@@ -331,56 +399,114 @@ checkPods(){
         afterRun ${exepods[@]}
     }
 
-    NS=$1
-    if [[ -z $NS ]]; then
-        echo -e "${RED}Namespace is not defined${NC}"
-        exit 1
+    if { [[ $2 =~ "help" ]] || [[ -z $3 || -z $2 ]]; }; then
+        if [[ -z $2 ]]; then
+            echo -e "${RED}Namespace is not defined${NC}"
+        fi
+        $1Help
     fi
+
+    NS=$2
 
     IFS=" " read -a pods <<< $(echo $(kubectl -n $NS get pods | grep -v "NAME" | awk '{print $1"@"$3"@"$4}'))
 
-    while [ -n $2 ]; do
-        case $2 in
-            err) err
-             ;;
-            warn) warn
-             ;;
-            *) all
-             ;;
+    while [ -n $3 ]; do
+        case $3 in
+            err) err $4
+            ;;
+            warn) warn $4
+            ;;
+            all) all $4
+            ;;
+            *) checkHelp
+            ;;
         esac
     done
 }
 
-expose(){
-    NS=$1
-    kind=$2
+# expose(){
+#     NS=$2
+#     kind=$3
+#     sport=$4
 
-    exposeHelp(){
-        echo "Usage: easykube expose [namespace] [kind]"
-        echo "Kinds:"
-        echo "  service, svc, s"
-        echo "  deployment, d"
-        echo "  pod"
-        exit 1
-    }
+#     exposeHelp(){
+#         echo "Usage: easykube expose [namespace] [kind] port(optional)"
+#         echo "Example: easykube expose demo svc 8080"
+#         echo "Kinds:"
+#         echo "  service, svc, s"
+#         echo "  deployment, d"
+#         echo "  pod"
+#         exit 1
+#     }
 
+#     case $kind in
+#         service|svc|c) resource="service"
+#         ;;
+#         deployment|d) resource="deployment"
+#         ;;
+#         pod) resource="pod"
+#         ;;
+#         *) exposeHelp
+#         ;;
+#     esac
 
+#     IFS=" " read -a items <<< $(echo $(kubectl -n $NS get $resource"s" | grep -v "NAME" | awk '{print $1"@"$5}'))
 
-    if { [[ $1 =~ "help" ]] || [[ -z $1 || -z $2 ]]; }; then
-        exposeHelp
-    fi
+#     if [[ -z $items ]]; then
+#         echo -e "\nNo $resource"s" available" && exit 1
+#     fi
 
-    case $2 in
-        service|svc|c) exposeSvc
-        break ;;
-        deployment|d) exposeDeployment
-        break ;;
-        pod) exposePod
-        break ;;
-        *) exposeHelp
-        break ;;
-    esac
-}
+#     for (( i=0; i<${#items[@]}; i++ )); do
+#         item=$(echo ${items[i]} | cut -d"@" -f1)
+#         port=$(echo ${items[i]} | cut -d"@" -f2 | cut -d"/" -f1)
+#         echo -e "   ${GREEN} [$i]: $item${NC}" | table3
+#         array+=($item)
+#     done
+
+#     echo -e "\nSelect number: \c"
+#     read -r c
+#     item=${array[c]}
+#     echo ""
+
+#     if [[ -z $sport ]]; then
+#         sport=$port
+#     fi
+
+#     handleConnection(){
+#         dir="/tmp/"
+#         file="hc-$(uuidgen).sh"
+#         echo "
+#         CONNFILE=$(echo $CONNFILE)
+#         kubectl -n $NS port-forward svc/$svc $sport/$port
+#         sleep 3600
+#         cat $CONNFILE | jq 'del(.connections | .[] | select(.name=='\"test1\"'))' > /tmp/easykube && cat /tmp/easykube > $CONNFILE
+#         exit 0" > $dir$file
+#         chmod +x $dir$file
+#         # cd $dir && ./$file > /dev/null 2>&1
+#         # pid=$!
+#         # if [[ $? -ne 0 ]]; then
+#         #     echo "Can't establish connection" && exit 1
+#         # fi
+
+#         check=cat $CONNFILE | jq '.connections | .[] | select(.name=='\"$NS\"')'
+#         if [[ ! -z $check ]]; then
+#             port=cat $CONNFILE | jq '.connections | .[] | select(.name=='\"$NS\"') | .port'
+#             pid=cat $CONNFILE | jq '.connections | .[] | select(.name=='\"$NS\"') | .pid'
+#             echo "$NS already exposed with port $port ($pid)" && exit 1
+#         fi
+#         echo "jq"
+#         cat $CONNFILE | jq '.[] + [{"name":'\"$NS\"', "port":'\"$sport\"', "pid":'\"$pid\"'}]' #> /tmp/easykube.conf && cat /tmp/easykube.conf > $CONFIGFILE
+#         echo "$resource $item available at http://127.0.0.1:$sport for a 1 hour"
+
+#     }
+
+#     echo ""
+#     echo -e "${YELLOW}$item selected${NC}"
+#     echo ""
+#     #kubectl -n $NS port-forward svc/$svc $sport/$port & 2>&1 /dev/null
+#     handleConnection $item $sport $port
+#     exit 0
+# }
 
 thisHelp(){
     echo "Easykube."
@@ -402,20 +528,20 @@ version(){
 if [[ $(kubectl config current-context) =~ "prod" ]]; then
     echo -e "${RED}ATTENTION"
     echo "PRODUCTION KUBECONFIG IS IN USE"
-    echo -e "PLEASE BE CAREFULL${NC}"
+    echo -e "PLEASE BE CAREFULL${NC}\n"
 fi
 
 while [ -n "$1" ]; do
     case $1 in
-        db) dbPass $2 $3 #ns, next call
+        db) dbPass $1 $2 $3 #option, ns, next call
         break ;;
-        exe) exe $2 $3 #ns command
+        exe|exec) exe $1 $2 $3 #option, ns command
         break ;;
-        check | c) checkPods $2 $3 #ns
+        check | c) checkPods "check" $2 $3 $4
         break ;;
-        logs | l) podLogs $2
+        logs | l) podLogs "logs" $2 #option, ns
         break ;;
-        # expose | e) exposePort $2 $3 #ns kind
+        # expose | e) expose "expose" $2 $3 $4 $5 #option, ns, kind,
         # break ;;
         version | v) version
         break ;;
